// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: event.proto

// Wire format for the events-raw Pub/Sub topic. The topic has this schema
// registered, and the BigQuery subscription consumes it via use_topic_schema.
//
// Field numbers, once assigned, are NEVER changed. Adding columns: append
// new fields with new tag numbers, then add the matching nullable column
// to the BigQuery table. Old messages will land with NULL for the new
// column. Removing or renaming columns is not supported — that is a new
// table.
//
// Timestamps are RFC3339 strings (e.g. "2026-05-09T12:00:00.000Z"), not
// google.protobuf.Timestamp. Pub/Sub Schema Registry rejects external
// imports, so we use plain strings; BQ subscriptions parse RFC3339 into
// TIMESTAMP columns natively.

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AnonymousId   string                 `protobuf:"bytes,4,opt,name=anonymous_id,json=anonymousId,proto3" json:"anonymous_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientTs      string                 `protobuf:"bytes,6,opt,name=client_ts,json=clientTs,proto3" json:"client_ts,omitempty"`
	ServerTs      string                 `protobuf:"bytes,7,opt,name=server_ts,json=serverTs,proto3" json:"server_ts,omitempty"`
	Platform      string                 `protobuf:"bytes,8,opt,name=platform,proto3" json:"platform,omitempty"`
	AppVersion    string                 `protobuf:"bytes,9,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	SdkVersion    string                 `protobuf:"bytes,10,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	AppId         string                 `protobuf:"bytes,11,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UaFamily      string                 `protobuf:"bytes,12,opt,name=ua_family,json=uaFamily,proto3" json:"ua_family,omitempty"`
	UaOs          string                 `protobuf:"bytes,13,opt,name=ua_os,json=uaOs,proto3" json:"ua_os,omitempty"`
	GeoCountry    string                 `protobuf:"bytes,14,opt,name=geo_country,json=geoCountry,proto3" json:"geo_country,omitempty"`
	IngestVersion string                 `protobuf:"bytes,15,opt,name=ingest_version,json=ingestVersion,proto3" json:"ingest_version,omitempty"`
	Properties    string                 `protobuf:"bytes,16,opt,name=properties,proto3" json:"properties,omitempty"`
	Context       string                 `protobuf:"bytes,17,opt,name=context,proto3" json:"context,omitempty"`
	GeoRegion     string                 `protobuf:"bytes,18,opt,name=geo_region,json=geoRegion,proto3" json:"geo_region,omitempty"`
	GeoCity       string                 `protobuf:"bytes,19,opt,name=geo_city,json=geoCity,proto3" json:"geo_city,omitempty"`
	GeoLat        string                 `protobuf:"bytes,20,opt,name=geo_lat,json=geoLat,proto3" json:"geo_lat,omitempty"`
	GeoLon        string                 `protobuf:"bytes,21,opt,name=geo_lon,json=geoLon,proto3" json:"geo_lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsEvent) Reset() {
	*x = AnalyticsEvent{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsEvent) ProtoMessage() {}

func (x *AnalyticsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsEvent.ProtoReflect.Descriptor instead.
func (*AnalyticsEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AnalyticsEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *AnalyticsEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyticsEvent) GetAnonymousId() string {
	if x != nil {
		return x.AnonymousId
	}
	return ""
}

func (x *AnalyticsEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnalyticsEvent) GetClientTs() string {
	if x != nil {
		return x.ClientTs
	}
	return ""
}

func (x *AnalyticsEvent) GetServerTs() string {
	if x != nil {
		return x.ServerTs
	}
	return ""
}

func (x *AnalyticsEvent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AnalyticsEvent) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *AnalyticsEvent) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *AnalyticsEvent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AnalyticsEvent) GetUaFamily() string {
	if x != nil {
		return x.UaFamily
	}
	return ""
}

func (x *AnalyticsEvent) GetUaOs() string {
	if x != nil {
		return x.UaOs
	}
	return ""
}

func (x *AnalyticsEvent) GetGeoCountry() string {
	if x != nil {
		return x.GeoCountry
	}
	return ""
}

func (x *AnalyticsEvent) GetIngestVersion() string {
	if x != nil {
		return x.IngestVersion
	}
	return ""
}

func (x *AnalyticsEvent) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

func (x *AnalyticsEvent) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *AnalyticsEvent) GetGeoRegion() string {
	if x != nil {
		return x.GeoRegion
	}
	return ""
}

func (x *AnalyticsEvent) GetGeoCity() string {
	if x != nil {
		return x.GeoCity
	}
	return ""
}

func (x *AnalyticsEvent) GetGeoLat() string {
	if x != nil {
		return x.GeoLat
	}
	return ""
}

func (x *AnalyticsEvent) GetGeoLon() string {
	if x != nil {
		return x.GeoLon
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\fanalytics.v1\"\xf4\x04\n" +
	"\x0eAnalyticsEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\fanonymous_id\x18\x04 \x01(\tR\vanonymousId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_ts\x18\x06 \x01(\tR\bclientTs\x12\x1b\n" +
	"\tserver_ts\x18\a \x01(\tR\bserverTs\x12\x1a\n" +
	"\bplatform\x18\b \x01(\tR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\t \x01(\tR\n" +
	"appVersion\x12\x1f\n" +
	"\vsdk_version\x18\n" +
	" \x01(\tR\n" +
	"sdkVersion\x12\x15\n" +
	"\x06app_id\x18\v \x01(\tR\x05appId\x12\x1b\n" +
	"\tua_family\x18\f \x01(\tR\buaFamily\x12\x13\n" +
	"\x05ua_os\x18\r \x01(\tR\x04uaOs\x12\x1f\n" +
	"\vgeo_country\x18\x0e \x01(\tR\n" +
	"geoCountry\x12%\n" +
	"\x0eingest_version\x18\x0f \x01(\tR\ringestVersion\x12\x1e\n" +
	"\n" +
	"properties\x18\x10 \x01(\tR\n" +
	"properties\x12\x18\n" +
	"\acontext\x18\x11 \x01(\tR\acontext\x12\x1d\n" +
	"\n" +
	"geo_region\x18\x12 \x01(\tR\tgeoRegion\x12\x19\n" +
	"\bgeo_city\x18\x13 \x01(\tR\ageoCity\x12\x17\n" +
	"\ageo_lat\x18\x14 \x01(\tR\x06geoLat\x12\x17\n" +
	"\ageo_lon\x18\x15 \x01(\tR\x06geoLonB5Z3github.com/example/event-pipeline/collector/eventpbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_proto_goTypes = []any{
	(*AnalyticsEvent)(nil), // 0: analytics.v1.AnalyticsEvent
}
var file_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
